version: '3.6'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    networks:
      - time-manager
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      SECRET_KEY_BASE: secret
      PORT: 4000
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - ./server:/server/app
    networks:
      - time-manager
  client:
      restart: always
      build:
        context: ./client
        dockerfile: Dockerfile
      networks:
        - time-manager
      environment:
        ENV: PROD
      depends_on:
        - server
        - db
      ports:
        - "80:8080"
volumes:
  pgdata:
networks:
  time-manager:
    driver: bridge