FROM bitwalker/alpine-elixir-phoenix:latest

WORKDIR /app

RUN mkdir assets

COPY . .

RUN mix local.hex --force && mix local.rebar --force && mix deps.clean --all && mix deps.update --all && mix deps.get

RUN apk add --no-cache make gcc libc-dev

RUN cd deps/bcrypt_elixir && make clean && make

RUN mix deps.compile

CMD mix ecto.create && mix ecto.migrate && mix run priv/repo/seeds.exs && mix phx.server