FROM bitwalker/alpine-elixir-phoenix:latest

WORKDIR /app

RUN mkdir assets


COPY . .

RUN mix local.hex --force && mix local.rebar --force && mix deps.clean --all && mix do deps.get, compile

CMD mix ecto.create && mix ecto.migrate && mix phx.server